https:
  host: "localhost"
  port: "8081"
  
canvas:
  token: "Bearer 7~VKBnJf6Qhk9mKHKY39mZ8w4TATRc6wcXRUH38JcvxEfZZHWhcvEGKX9vWhTY9vLV"
  baseUri: "https://canvas.instructure.com/api/v1"

sf:
  username: "aurosmit.sahoo@nexturn.comauro.edu"
  password: "Aurosmit@2001"
  securityToken: "mlXoqVnVqAN6ciAVNNYyGG9Xz"